dependencies:
  - name: postgresql
    version: 8.2.0
    repository: ../postgresql/
    condition: postgresql.enabled
  - name: mysql
    version: 0.6.0
    repository: ../mysql/
    condition: mysql.enabled
